### ISSUE TITLE
Need version for react@v18.2.0

### ISSUE THREAD

**Issue by kochfoto** [vre2h/use-react-screenshot#57]
I'm attempting to use with in a project but I'm getting `npm ERR! code ERESOLVE` because my project is using react@v18.2.0 and use-react-screenshot is in react@v17.0.2. I'm not sure how to resolve this. Any guidance would be appreciated.

**Comment by KlokMiraj** [comment]
Can I work on this issue ?
Thanks

**Comment by ojonah** [comment]
> Can I work on this issue ? Thanks

If you work on this will you notify us in this repo or share a link so i can follow your update?

**Comment by pudasainimiraj** [comment]
> > Can I work on this issue ? Thanks
> 
> If you work on this will you notify us in this repo or share a link so i can follow your update?

Hi Ojonah, 
This issue has been completed solved and merged.
Thank you

**Comment by vre2h** [comment]
Hi guys. Sorry for being inactive. Merged the pr and published. Going to pay more attention to lib and fix errors.

**Comment by kochfoto** [comment]
Amazing! Thank you for updating this.
