### ISSUE TITLE
screenshot different from DOM

### ISSUE THREAD

**Issue by fcpauldiaz** [vre2h/use-react-screenshot#7]
The screenshot is adding some gray shadows (right and bottom) that are not in the DOM, is there a way to fix this?

![Screen Shot 2021-12-06 at 17 43 34](https://user-images.githubusercontent.com/4523284/144940288-cf836d40-0eab-497b-9bee-d3e16b74c2cd.png)

**Comment by fcpauldiaz** [comment]
Actually, this is related to html2canvas, so closing it

**Comment by shiraleeana** [comment]
Hi @fcpauldiaz – did you figure out how to get rid of the shadows?

**Comment by fcpauldiaz** [comment]
Hi @shiraleeana the shadows are an issue of the underlying library `html2canvas`. The workaround I'm using is disabling the shadows of the components only right before taking the screenshot and then re-enabling them after.

**Comment by shiraleeana** [comment]
Ok I see. Thanks for that.

**Comment by shiraleeana** [comment]
Found a solution for myself:
I just had a box shadow on my "card" which needed to be screenshot.
So I added an extra div inside the card and used that as the `ref` for the screenshot instead – no shadow issues.

**Comment by requenahdz** [comment]
The dropdown has to be outside of your reference
